Add controllers
Bikochu/java-shareit pull request #2
Opened 2023-04-28 15:51 UTC by Bikochu

2023-04-29 14:42 UTC, Donald522 requested changes

2023-04-29 14:42 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemController(ItemService itemService) {
Можно заменить на аннотацию RequiredArgsConstructor

2023-04-29 14:42 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        return null;
А почему тут не реализована конвертация?

2023-04-29 14:42 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    private final List<Item> items = new ArrayList<>();
Почему список?
Какая сложность поиска в списке?

2023-04-29 14:42 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<Item> getItemsByUser(@RequestHeader(value = "X-Sharer-User-Id", required = true) Long userId) {
Возвращаем наружу Dto объект

2023-04-29 14:42 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                        @Valid @RequestBody Item item) {
Принимаем тоже dto объект

2023-04-29 14:42 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +public class UserController {
В этом классе тоже надо использовать dto объекты на входе/выходе

2023-05-01 09:36 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemController(ItemService itemService) {
Сделал так же в UserController.

2023-05-01 09:56 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        return null;
Реализовал, но так как пока мы не делаем ItemRequest, оставил в Item поле request - null.

2023-05-01 10:53 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +public class UserController {
Реализовал UserDto во всех методах.

2023-05-01 12:23 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    private final List<Item> items = new ArrayList<>();
Исправил на HashMap, сложность при поиске и О(1). Так же сделал и в UserService.

2023-05-01 12:23 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<Item> getItemsByUser(@RequestHeader(value = "X-Sharer-User-Id", required = true) Long userId) {
Исправил.

2023-05-01 12:24 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                        @Valid @RequestBody Item item) {
Исправил во всем классе.

2023-05-01 14:50 UTC, felixoff commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private LocalDate start;
Вместо множественных private лучше использовать @FieldDefaults для избежания дублирования

2023-05-01 14:50 UTC, felixoff commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto updateItem(@RequestHeader(value = "X-Sharer-User-Id", required = true) Long userId,
Хедер много раз повторяется. Можно вынести в отдельную переменную

2023-05-01 16:26 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto updateItem(@RequestHeader(value = "X-Sharer-User-Id", required = true) Long userId,
Вынес в переменную header

2023-05-01 16:26 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private LocalDate start;
Добавил в классы @FieldDefaults(level = AccessLevel.PRIVATE)

2023-05-02 19:13 UTC, merged