Add: Booking, Comment, Time.
Bikochu/java-shareit pull request #3
Opened 2023-05-19 15:15 UTC by Bikochu

2023-05-19 19:56 UTC, Donald522 requested changes
Привет!

Самое главное - нельзя доставать из базы все данные и фильтровать на уровне приложения. Даже при не очень больших объемах это перестанет работать. Максимум логики надо переносить в запрос и стараться достать из БД как можно меньше данных.

В остальном все нормально.

2023-05-19 19:56 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoIn.java
> +public class BookingDtoIn {
Лучше было бы BookingRequestDto

Названия классов, особенно модельных классов, очень важны

2023-05-19 19:56 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                .filter(booking -> booking.getBooker().getId().equals(userId))
Вся фильтрация должна делаться на стороне хранилища

Мы не можем тащить всю базу через сеть в память приложения, чтобы потом отфильтровать по user_id

Ко всем методам относится

2023-05-19 19:56 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            default:
Вместо ветки default можно было привести строку к enum. Не просто же так мы его создали?

2023-05-19 19:56 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                throw new UnsupportedStateException("Unknown state: UNSUPPORTED_STATUS");
В текст ошибки надо бы добавить статус, которым нам передали

2023-05-19 19:56 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<BookingDtoIn> bookings = bookingRepository.findAll().stream()
Та же ошибка с запросами

2023-05-19 19:56 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (existingComment != null) {
Пользователь не сможет написать 2 отзыва на 1 предмет? Это странно, я бы так не делал

2023-05-19 19:56 UTC, Donald522 requested changes
Привет!

Самое главное - нельзя доставать из базы все данные и фильтровать на уровне приложения. Даже при не очень больших объемах это перестанет работать. Максимум логики надо переносить в запрос и стараться достать из БД как можно меньше данных.

В остальном все нормально.

2023-05-19 19:57 UTC, Donald522 requested changes
Привет!

Самое главное - нельзя доставать из базы все данные и фильтровать на уровне приложения. Даже при не очень больших объемах это перестанет работать. Максимум логики надо переносить в запрос и стараться достать из БД как можно меньше данных.

В остальном все нормально.

2023-05-19 20:11 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoIn.java
> +public class BookingDtoIn {
Исправил!

2023-05-19 20:17 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            default:
Добавил enum: UNSUPPORTED_STATUS и изменил default на вывод ALL;

2023-05-19 20:21 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                throw new UnsupportedStateException("Unknown state: UNSUPPORTED_STATUS");
Исправил! throw new UnsupportedStateException("Unknown state: "+state);

2023-05-19 20:52 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                .filter(booking -> booking.getBooker().getId().equals(userId))
Добавил в репозиторий метод findAllByBookerIdOrderByStartDesc и findAllByItemOwnerIdOrderByStartDesc

2023-05-19 21:31 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<BookingDtoIn> bookings = bookingRepository.findAll().stream()
Добавил еще несколько методов в BookingRepository.

2023-05-19 21:40 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (existingComment != null) {
Исправил, теперь нельзя комментировать несколько раз один и тот же предмет.

2023-05-19 21:45 UTC, Bikochu commented
Исправил согласно вашим рекомендациям. Постарался максимально перенести логику выборки из БД в запрос в репозиторий.

2023-05-21 09:41 UTC, Donald522 approved these changes
Привет!
Сейчас намного лучше. Но фильтрацию лучше до конца вынести в БД и все еще не понятно про использование State.

Поправь в следующем спринте эти моменты.

2023-05-21 09:41 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        LocalDateTime currentDateTime = LocalDateTime.now();
В now в качестве параметра советую передавать объект Clock. Это упростит написание тестов

2023-05-21 09:41 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (existingComment != null) {
Ну это спорная логика. Почему нельзя комментить один и тот же предмет несколько раз?

2023-05-21 09:41 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .filter(booking1 -> booking1.getStatus().equals("WAITING"))
Эту фильтрацию тоже бы перенести в БД

2023-05-21 09:41 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            default:
Как у тебя вообще enum используется? У тебя тут стейт это String.
Мой коммент был про то, чтобы использовать тут enum, а не строки.

2023-05-21 09:41 UTC, Donald522 approved these changes
Привет!
Сейчас намного лучше. Но фильтрацию лучше до конца вынести в БД и все еще не понятно про использование State.

Поправь в следующем спринте эти моменты.

2023-05-21 20:56 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        LocalDateTime currentDateTime = LocalDateTime.now();
Доработал согласно вашей рекомендации. Добавил переменную LocalDateTime now = LocalDateTime.now(Clock.systemDefaultZone());

2023-05-21 20:59 UTC, Bikochu commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .filter(booking1 -> booking1.getStatus().equals("WAITING"))
Убрал единый метод getBookingsWithState и перенес логику в методы для Owner и для Booker.
Также убрал фильтрацию в методы репозитория JpaRepository.

2023-05-21 20:59 UTC, Bikochu commented
Спасибо за ценные советы. Исправил согласно вашим рекомендациям.

2023-05-23 19:07 UTC, merged