Add docker
Bikochu/java-shareit pull request #6
Opened 2023-06-15 09:52 UTC by Bikochu

2023-06-15 20:24 UTC, Donald522 requested changes
Привет!

Оставил парочку замечаний

2023-06-15 20:24 UTC, Donald522 commented on docker-compose.yml
> +      - POSTGRES_USER=root
Давай не ходить в бд под рутом из приложения

2023-06-15 20:24 UTC, Donald522 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    /*public ResponseEntity<Object> getBookings(long userId, BookingState state, Integer from, Integer size) {
Комменты надо удалить

2023-06-15 20:24 UTC, Donald522 commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Этой зависимости не должно быть больше в сервере

2023-06-15 21:53 UTC, Bikochu commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Действительно, спасибо, убрал.

2023-06-15 22:03 UTC, Bikochu commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +														  @RequestParam(name = "state", defaultValue = "all") String stateParam,
Подкорректировал форматирование.

2023-06-15 22:09 UTC, Bikochu commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    /*public ResponseEntity<Object> getBookings(long userId, BookingState state, Integer from, Integer size) {
Удалил.

2023-06-15 22:10 UTC, Bikochu commented on docker-compose.yml
> +      - POSTGRES_USER=root
Вход оставил только через server.

2023-06-16 19:48 UTC, Donald522 approved these changes

2023-06-16 21:40 UTC, merged